### ISSUE TITLE
剩余事宜

### ISSUE THREAD

**Issue by mzz2017** [Actooors/LabManagementSystem_web#2]
## deadline: 本周四（第十周周四）
- [x] 演讲PPT

## deadline: 下周五（第十一周周五）
- [x] 课程项目报告
- [x] 光盘：①课程项目代码、数据库文件及其配置文件；②课程项目报告；③课程项目演讲PPT。将以上1中所有材料电子版刻录光盘一张，并在光盘盒上注明信息：①项目编号；②项目名称。

**Comment by mzz2017** [comment]
### PPT相关
采用知识点（前端）:
1. Vue.js
2. AJAX
3. Element-UI

采用知识点（后端）：
@0GGmr0 

总体：
RESTful实现前后端分离

**Comment by 0GGmr0** [comment]
后端 spring
         springboot 
         mabatis
         mybatis反向工程
